export const ROUTES = {
  HOME: '/',

  PROJECTS: '/projects',
  TICKET_DETAILS: (projectSlug: string, ticketSlug: string) => `/projects/${projectSlug}/tickets/${ticketSlug}`,
  BOARD_DETAILS: (projectSlug: string, boardId: number) => `/projects/${projectSlug}/boards/${boardId}`,
  BOARDS: (projectSlug: string) => `/projects/${projectSlug}/boards`,
  TICKETS_LIST: (projectSlug: string) => `/projects/${projectSlug}/tickets/all`,
  PASSWORDS_ENTRIES: (environmentId: number) => `/passwords/${environmentId}/entries`,
  TICKETS_BOARD_VIEW: (projectSlug: string) => `/projects/${projectSlug}/tickets`,
  PROJECTS_PAGES: (projectSlug: string) => `/projects/${projectSlug}/pages`,
  PROJECT_DETAILS: (projectSlug: string) => `/projects/${projectSlug}`,
  PROJECTS_PAGE_DETAILS: (projectSlug: string, pageId: number) => `/projects/${projectSlug}/pages/${pageId}`,
  BOARD_STRUCTURE: (projectSlug: string) => `/projects/${projectSlug}/tickets-board-structure`,
  ASSET_DETAILS: (assetId: number) => `/assets/${assetId}`,


  DASHBOARD: '/dashboard',
  PROJECT: '/projects/:slug',
  LOGIN: '/login',
  REGISTER: '/register',
  PROFILE: '/profile',
  SETTINGS: '/settings',
  STATUS: '/status',
  FINANCE_DASHBOARD: '/finances',
  ASSETS: '/assets',
  PASSWORDS: '/passwords',
  FINANCE_DETAILS: '/finances/details',
  FINANCE_SUMMARY: '/finances/summary',
  NOT_FOUND: '/404',
  LOGOUT: '/logout',
};
